language: python

python:
  - "3.7.6"

before_script:
  - cd purbeurre/
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - cd purbeurre/
  - python manage.py test food.tests -v 2
  - python manage.py test member.tests -v 2

branches:
  only:
    - tempo
